### ISSUE TITLE
Setup basic react app in learning-app-ui project

### ISSUE THREAD

**Issue by keith-wilde** [keith-wilde/learning-app-ui#1]
Get the basic codebase created and pushed to my repo.

**Comment by Owenzo7** [comment]
Could you assign me this role kindly.

**Comment by keith-wilde** [comment]
Hi, so I was creating this learning-app stuff specifically to learn more
about react and ui development. I would be open to maybe collaborating on
something else.

**Comment by Owenzo7** [comment]
Yeah sure thing maybe kindly accept my pull request and check whether all is well. On the terminal on your vs code after you have merged my changes just run the command npm run install. You shall see it initialize a start up react kind of project that you can work your idea on. It was nice talking to you and yes I am looking forward on collaborating with your Sir. Let's follow each other. Shall we??

**Comment by keith-wilde** [comment]
Sounds good, I will check it out probably tonight or tomorrow. I have never
really used GitHub that much before for my own stuff.

**Comment by Owenzo7** [comment]
Nah dont worry man. Github is actually easy to learn man. Anyways its night time on my side so I just want to wish you a good evening sir!!
